"""
Centralized runtime paths.

This module defines canonical locations for local runtime data generated by the
CLI (agent memory, chart exports), with optional environment-variable overrides.
"""

import os
from pathlib import Path

# Base directory for runtime data generated by the CLI.
# Defaults to the project root to preserve current behavior.
_RUNTIME_BASE = Path(os.getenv("SIMPLE_RAG_RUNTIME_DIR", ".")).resolve()

# ChromaDB persistence directory used by the agent memory.
CHROMA_DB_DIR = Path(
    os.getenv("SIMPLE_RAG_CHROMA_DIR", str(_RUNTIME_BASE / "chroma_db_vanna"))
).resolve()

# Chart export directory used by the CLI formatter.
CHART_EXPORT_DIR = Path(
    os.getenv("SIMPLE_RAG_CHART_DIR", str(_RUNTIME_BASE / "exports" / "charts"))
).resolve()

# JSONL audit log directory and file for interactions.
AUDIT_LOG_DIR = Path(
    os.getenv("SIMPLE_RAG_AUDIT_DIR", str(_RUNTIME_BASE / "exports" / "audit"))
).resolve()
AUDIT_LOG_FILE = AUDIT_LOG_DIR / "interactions.jsonl"


def ensure_runtime_dirs() -> None:
    """Create runtime directories when missing."""
    CHROMA_DB_DIR.mkdir(parents=True, exist_ok=True)
    CHART_EXPORT_DIR.mkdir(parents=True, exist_ok=True)
    AUDIT_LOG_DIR.mkdir(parents=True, exist_ok=True)
